Minor tests for utils and Exception
jymfony/jymfony pull request #1
Opened 2017-01-08 22:00 UTC by massimilianobraglia

I have added some minor tests in `jymfony-exception` and `jymfony-util`. Please, review the exception part, because my environment had some test execution problems.

2017-01-08 22:23 UTC, alekitto requested changes

2017-01-08 22:23 UTC, alekitto commented on src/util/lib/String/escapeshellarg.js
> -global.__jymfony.escapeshellarg = function escapeshellarg (arg) {
Please let global functions to have its own name and `this`

2017-01-08 22:23 UTC, alekitto commented on src/util/lib/String/escapeshellarg.js
> +    return `'${arg.replace(/[^\\]'/g, m => m.slice(0, 1) + '\\\'')}'`;
In this particular case I find the previous version clearer.
In general i prefer string interpolation of simple expressions (a variable or a property access, also via a getter) and concatenation for more complex expressions like this.

2017-01-08 22:23 UTC, alekitto commented on src/util/test/String/LevenshteinTest.js
> +describe('Levenshtein distance', () => {
Please do not use arrow functions in the `describe` function call. The reason is explained here: https://mochajs.org/#arrow-functions

2017-01-08 22:23 UTC, alekitto commented on src/util/test/String/TrimTest.js
> +require('../../lib/String/ucwords');
Did you mean: `../../lib/String/trim`?

2017-01-08 22:23 UTC, alekitto commented on src/util/test/String/UcFirstTest.js
> +require('../../lib/String/ucwords');
Same here: wrong file requested

2017-01-08 22:48 UTC, massimilianobraglia commented on src/util/lib/String/escapeshellarg.js
> -global.__jymfony.escapeshellarg = function escapeshellarg (arg) {
oh, ok! Didn't thought about that point

2017-01-08 22:49 UTC, massimilianobraglia commented on src/util/test/String/LevenshteinTest.js
> +describe('Levenshtein distance', () => {
+1

2017-01-08 22:57 UTC, massimilianobraglia commented on src/util/lib/String/escapeshellarg.js
> +    return `'${arg.replace(/[^\\]'/g, m => m.slice(0, 1) + '\\\'')}'`;
I understand your point of view, but this case was clear enough.
Anyway, no problem, reverting

2017-01-08 23:01 UTC, alekitto commented on src/util/lib/String/escapeshellarg.js
> +    return `'${arg.replace(/[^\\]'/g, m => m.slice(0, 1) + '\\\'')}'`;
Thinkin' about it: we should define it better and write down a code style rules documentation file

2017-01-08 23:05 UTC, massimilianobraglia commented on src/util/lib/String/escapeshellarg.js
> +    return `'${arg.replace(/[^\\]'/g, m => m.slice(0, 1) + '\\\'')}'`;
You know me: it is fundamental to have a CS rule file :)

2017-01-09 17:00 UTC, alekitto approved these changes

2017-01-09 17:01 UTC, merged