[FrameworkBundle] KernelInterface and Application class
jymfony/jymfony pull request #2
Opened 2017-08-02 16:58 UTC by massimilianobraglia

Implemented KernelInterface and FrameworkBundle.Console.Application class.

ApplicationTest is in progress.

2017-08-02 23:02 UTC, alekitto requested changes
Looks good for now. I just left some comments.

2017-08-02 23:02 UTC, alekitto commented on package.json
> +    "test": "node ./tests.js \"src/*/test/**/*.js\" \"src/Component/*/test/**/*.js\" \"src/Bundle/*/test/**/*.js\"",
Comma separated names should be a valid glob. Please use `src/{Bundle,Component}/*/test/**/*.js` instead of adding a new path.

2017-08-02 23:02 UTC, alekitto commented on src/Bundle/FrameworkBundle/fixtures/BarCommand.js
> +    * interact(input, output) {
Not a generator.
While overriding these methods you're not forced to define them as generators. Give the Async runner an hint telling it that you're not `yield`-ing any promise.

2017-08-02 23:02 UTC, alekitto commented on src/Component/Console/src/Application.js
> +     * @return {string} A help message
`@returns`

2017-08-02 23:02 UTC, alekitto commented on src/Component/Kernel/var/cache/appTestDebugProjectContainer.js
> +const Container = Jymfony.Component.DependencyInjection.Container;
Remove this.

2017-08-02 23:02 UTC, alekitto commented on src/Component/Kernel/var/cache/appTestDebugProjectContainer.js.meta
> +A(17):{0:C[Jymfony.Component.Config.Resource.FileResource]:{S(11):"_resource":S(80):"/Users/massimilianobraglia/projects/jymfony/src/Component/Kernel/src/Kernel.js";};1:C[Jymfony.Component.Config.Res
Remove this.

2017-08-02 23:02 UTC, alekitto commented on src/Bundle/FrameworkBundle/src/Console/Application.js
> +        return super._doRun(input, output);
I'm no more convinced that this is the correct way to call a parent generator.
We should test it, but I think that a delegate yield is needed here.

2017-08-03 07:56 UTC, massimilianobraglia commented on package.json
> +    "test": "node ./tests.js \"src/*/test/**/*.js\" \"src/Component/*/test/**/*.js\" \"src/Bundle/*/test/**/*.js\"",
+1

2017-08-03 07:58 UTC, massimilianobraglia commented on src/Bundle/FrameworkBundle/fixtures/BarCommand.js
> +    * interact(input, output) {
That's a good point. Said that, other fixtures command should be fixed this way.

2017-08-04 09:21 UTC, alekitto approved these changes

2017-08-04 09:22 UTC, merged