[FrameworkBundle] Add Compiler to FrameworkBundle
jymfony/jymfony pull request #3
Opened 2017-08-03 10:29 UTC by giovannialbero1992

- [x] RegisterListenersPass
- [ ] AddCacheWarmerPass
- [ ] AddCacheClearerPass
- [ ] UnusedTagsPass
- [ ] ContainerBuilderDebugDumpPass
- [ ] AddConsoleCommandPass
- [ ] CacheCollectorPass

2017-08-03 13:33 UTC, alekitto requested changes
Added some style comments.
ReflectionClass `isSubclassOf` is needed to complete this task. Tracking it in #5

2017-08-03 13:33 UTC, alekitto commented on src/Component/DependencyInjection/src/Argument/ServiceClousureArgument.js
> +    __constructor(reference) {
Typo: `__construct`

2017-08-03 13:33 UTC, alekitto commented on src/Component/DependencyInjection/src/Argument/ServiceClousureArgument.js
> +    getValues() {
Use `get values()` and `set values(values)` 

2017-08-03 13:33 UTC, alekitto commented on src/Component/EventDispatcher/src/DependencyInjection/Compiler/RegisterListenerPass.js
> +                let priority = event['priority'] !== undefined ? event['priority'] : 0;
Prefer dot notation (`event.priority` instead of `event['priority']`) if using non-numeric, non-dynamic properties.

2017-08-03 13:33 UTC, alekitto commented on src/Component/EventDispatcher/src/DependencyInjection/Compiler/RegisterListenerPass.js
> +            if (! myclass.prototype instanceof myInterface) {
Probably wrong check here. `isSubclassOf` is missing: tracked in #5

2017-08-03 13:33 UTC, alekitto commented on src/Component/EventDispatcher/src/DependencyInjection/Compiler/RegisterListenerPass.js
> +    static set subscriber(subscriber) {
Misleading `this` used in static context. If you really want to define a static property, prefer using the class name instead of `this`.

2017-08-03 14:38 UTC, alekitto commented
@giovannialbero1992 Issue #5 is closed and `ReflectionClass.isSubclassOf` is now available. Please rebase and use where needed.

2017-08-03 14:39 UTC, giovannialbero1992 commented
thanks

2017-08-03 16:38 GMT+02:00 Alessandro Chitolina <notifications@github.com>:

> @giovannialbero1992 <https://github.com/giovannialbero1992> Issue #5
> <https://github.com/jymfony/jymfony/issues/5> is closed and
> ReflectionClass.isSubclassOf is now available. Please rebase and use
> where needed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jymfony/jymfony/pull/3#issuecomment-319988610>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ALAKUVQz2wssaH1qcAkBJV9QBQXqI4Vqks5sUduCgaJpZM4OsQTr>
> .
>



-- 
*Giovanni Albero*
+393661860916
giovannialbero.solinf@gmail.com
full-stack developer
Skype: giovanni.albero
Linkedin: https://it.linkedin.com/pub/giovanni-albero/64/465/bba
Twitter: @albero92

2017-08-04 07:51 UTC, alekitto requested changes
Looks good. Only style fixes required.

2017-08-04 07:51 UTC, alekitto commented on src/Component/DependencyInjection/src/Argument/ArgumentInterface.js
> +     */
Please explicit methods in this interface.
In addition, the correct way to document an array is `{[type]}`, where `type` can be a base type, `*` or a class name.

2017-08-04 07:51 UTC, alekitto commented on src/Bundle/FrameworkBundle/src/DependencyInjection/Compiler/AddCacheWarmerPass.js
> +const CompilerPassInterface = Jymfony.DependencyInjection.CompilerPassInterface;
Remove this file.

2017-08-04 07:51 UTC, alekitto commented on src/Component/DependencyInjection/src/Argument/ServiceClousureArgument.js
> +class ServiceClousureArgument extends implementationOf(ArgumentInterface) {
JSDoc missing. Please add at least the `@memberOf` annotation.

2017-08-04 07:51 UTC, alekitto commented on src/Component/DependencyInjection/src/Argument/ServiceClousureArgument.js
> +     * @return {Array|*}
Correct annotation is `@returns {[*]}`. Please fix all the `@return` adding the missing "s"

2017-08-04 07:51 UTC, alekitto commented on src/Component/EventDispatcher/src/EventSubscriberInterface.js
> +     * @return array The events name to listen to
Same as above.

2017-08-04 07:51 UTC, alekitto commented on src/Component/EventDispatcher/src/EventSubscriberInterface.js
> +     *  * ['eventName' => [['methodName1', priority] ['methodName2']]]
Fix this doc using correct js notation for objects and arrays.

2017-08-04 07:51 UTC, alekitto commented on src/util/lib/Object/sort.js
> +
Remove extra empty line.

2017-08-04 08:31 UTC, alekitto approved these changes

2017-08-04 08:31 UTC, alekitto commented
Waiting for green to merge.

2017-08-04 09:19 UTC, merged